### PR TITLE
Adding support for dates

### PR DESCRIPTION
**Pull request by anthonydipaola2**

### CODE REVIEW

**Comment by PeterWippermann** [comment]
Please don't use the old `Date` class. The [Java Data Time API](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) has been out for years now and is well established.

**Comment by mdeanda** [comment]
hmm yeah i didn't realise there was a pull request. i like the idea but would like to limit the range of dates and times and it i think something like `getFutureDate(Duration duration)` is simple enough to use.

**Comment by Tc2r1** [comment]
A whole year and this still isn't resolved, what's up? Do I need to take a look at it? Honestly its the last bit of code I need from this lib lol

**Comment by graemeg** [comment]
> A whole year and this still isn't resolved, what's up? Do I need to take a look at it? Honestly its the last bit of code I need from this lib lol

It's got past & future dates already implemented, as can be seen [here](https://github.com/mdeanda/lorem/blob/master/src/main/java/com/thedeanda/lorem/LoremIpsum.java#L430..L443).

**Pull request closed without merging**
